import React, { useEffect, useState } from 'react'

import { Loader, Card, Form } from '../components'

const RenderCards = ({ data, title }) =>
{
    if (data?.length > 0) return data.map((post) => <Card key={post._id} {...post}/>)
    return (
        <h2 className='mt-5 font-bold text-[#6469fff] text-xl uppercase'>
            {title}
        </h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false)
    const [allPosts, setAllPosts] = useState(null)
    const [searchText, setSearchText] = useState('')
    const [searchedRes, setSearchedRes] = useState(null)
    const [searchTimeout, setSearchTimeout] = useState(null)

    useEffect(() =>
    {
        const fetchPosts = async() =>
        {
            setLoading(true)


            try
            {
                const res = await fetch('http://localhost:8080/api/v1/post',
                {
                    method: 'GET',
                    headers: { 'Content-Type': 'application/json' }
                })

                if (res.ok)
                {
                    const result = await res.json()
                    setAllPosts(result.data.reverse())
                }
            }
            catch(err)
            {
                alert(err)
            }
            finally
            {
                setLoading(false)
            }
        }
        
        fetchPosts()
    }, [])

    const HandleSearch = (e) =>
    {
        clearTimeout(searchTimeout)

        setSearchText(e.target.value)

        setSearchTimeout(
            setTimeout(() =>
            {
                const res = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()))
                setSearchedRes(res)
            }, 500)
        )

    }

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>Community Showcase</h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>Browse through a collection of imaginative annd visually stunnig images generated by synthart</p>
        </div>
        <div className='mt-16'>
            <Form
                labelName='Search posts'
                type='text'
                name='text'
                placeholder='Search...'
                value={searchText}
                HandleChange={HandleSearch}
            />
        </div>
        <div className='mt-10'>
            {loading ? 
            (
                <div className='flex justify-center items-center'>
                    <Loader/>
                </div>
            ) : 
            (
                <>
                    {searchText &&
                    (
                        <h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing results for <span className='text-[#222328]'>{searchText}</span></h2>
                    )}
                    <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                        {searchText ?
                        (
                            <RenderCards
                                data={searchedRes}
                                title="No search results found"
                            />
                        ) : 
                        (
                            <RenderCards
                                data={allPosts}
                                title="No posts found"
                            />
                        )}
                    </div>
                </>
            )}
        </div>
    </section>
  )
}

export default Home